name: Deploy Proxy to Digital Ocean

on:
  push:
    branches:
      - main
  create:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Determine version
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "v0.1.0")
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        platforms: linux/amd64, linux/arm64

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v3 
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/proxy-service:${{ env.TAG }}
            ${{ secrets.DOCKER_USERNAME }}/proxy-service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/proxy-service:latest
          cache-to: type=inline

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_ID }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/proxy-service:${{ env.VERSION }}
            docker service update --image ${{ secrets.DOCKER_USERNAME }}/proxy-service/${{ env.VERSION }}
